# Generated by Django 4.2.3 on 2023-07-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_user_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='hassen',
        ),
    ]
