# Generated by Django 4.2.3 on 2023-07-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='asma',
        ),
    ]
